import cx_Oracle

# Configuração de conexão (ajuste para seu ambiente Oracle)
USER = "usuario"
PASSWORD = "senha"
DSN = "localhost/XE"

def conectar_oracle():
    try:
        conn = cx_Oracle.connect(USER, PASSWORD, DSN)
        return conn
    except Exception as e:
        print("Erro ao conectar ao Oracle:", e)
        return None

def criar_tabela():
    conn = conectar_oracle()
    if conn:
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE colheitas (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tipo VARCHAR2(20),
                prod_estimada FLOAT,
                prod_real FLOAT,
                valor_tonelada FLOAT,
                perda_percentual FLOAT,
                prejuizo FLOAT,
                data VARCHAR2(50)
            )
        """)
        conn.commit()
        cursor.close()
        conn.close()

def inserir_dados(dados):
    conn = conectar_oracle()
    if conn:
        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO colheitas (tipo, prod_estimada, prod_real, valor_tonelada, perda_percentual, prejuizo, data)
            VALUES (:tipo, :prod_estimada, :prod_real, :valor_tonelada, :perda_percentual, :prejuizo, :data)
        """, dados)
        conn.commit()
        cursor.close()
        conn.close()

def listar_dados():
    conn = conectar_oracle()
    if conn:
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM colheitas")
        registros = cursor.fetchall()
        cursor.close()
        conn.close()
        return registros
